name: open_ai_utilities
description: "OpenAI Utilities"
version: 1.0.2
homepage: none
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dart_openai: ^5.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  file_picker: ^8.1.2
  flutter_markdown: ^0.7.3+1
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  hive_flutter: 1.1.0
  intl: ^0.19.0
  layout: ^1.0.5
  path: ^1.9.0
  path_provider: ^2.1.4
  universal_io: ^2.2.2

  flutter_highlighting:
    git:
      url: https://github.com/chirag729/dart-highlighting.git
      path: flutter_highlighting
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  flutter_lints: any
  isar_generator: ^3.1.0+1
  hive_generator: ^2.0.1

flutter:
